"""adiciona tabelas politicians e politician_votes

Revision ID: 13da3f6ba927
Revises: aef2a5c023fc
Create Date: 2026-06-07 11:12:41.932237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13da3f6ba927'
down_revision: Union[str, Sequence[str], None] = 'aef2a5c023fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('house', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('votes_in_favor', sa.Integer(), nullable=True),
    sa.Column('votes_against', sa.Integer(), nullable=True),
    sa.Column('abstentions', sa.Integer(), nullable=True),
    sa.Column('projects_presented', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicians_external_id'), 'politicians', ['external_id'], unique=True)
    op.create_index(op.f('ix_politicians_id'), 'politicians', ['id'], unique=False)
    op.create_index(op.f('ix_politicians_name'), 'politicians', ['name'], unique=False)
    op.create_index(op.f('ix_politicians_party'), 'politicians', ['party'], unique=False)
    op.create_index(op.f('ix_politicians_state'), 'politicians', ['state'], unique=False)
    op.create_table('politician_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('project_external_id', sa.String(), nullable=False),
    sa.Column('project_title', sa.String(), nullable=True),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('vote_date', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politician_votes_id'), 'politician_votes', ['id'], unique=False)
    op.create_index(op.f('ix_politician_votes_politician_id'), 'politician_votes', ['politician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politician_votes_politician_id'), table_name='politician_votes')
    op.drop_index(op.f('ix_politician_votes_id'), table_name='politician_votes')
    op.drop_table('politician_votes')
    op.drop_index(op.f('ix_politicians_state'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_party'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_name'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_id'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_external_id'), table_name='politicians')
    op.drop_table('politicians')
    # ### end Alembic commands ###
