"""adiciona tabela ods e coluna sincronizado

Revision ID: 4db6efc720ac
Revises: 6d80a2d47bce
Create Date: 2026-06-01 08:48:51.023812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db6efc720ac'
down_revision: Union[str, Sequence[str], None] = '6d80a2d47bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sincronizado', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_ano'), 'projects', ['ano'], unique=False)
    op.create_index(op.f('ix_projects_tipo'), 'projects', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tipo'), table_name='projects')
    op.drop_index(op.f('ix_projects_ano'), table_name='projects')
    op.drop_column('projects', 'sincronizado')
    # ### end Alembic commands ###
