"""adiciona tabelas tema, classificacao, tag e relacionamentos

Revision ID: 6d80a2d47bce
Revises: 
Create Date: 2026-05-28 06:58:35.965393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d80a2d47bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tag', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('referencia_id', sa.String(), nullable=False),
    sa.Column('referencia_tipo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_index(op.f('ix_tags_tipo_tag'), 'tags', ['tipo_tag'], unique=False)
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_tema', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temas_cod_tema'), 'temas', ['cod_tema'], unique=True)
    op.create_index(op.f('ix_temas_id'), 'temas', ['id'], unique=False)
    op.create_index(op.f('ix_temas_nome'), 'temas', ['nome'], unique=False)
    op.create_table('classificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('ods_numero', sa.Integer(), nullable=False),
    sa.Column('ods_nome', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confianca', sa.String(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposicao_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classificacoes_id'), 'classificacoes', ['id'], unique=False)
    op.create_table('proposicao_tema',
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('tema_cod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tema_cod'], ['temas.cod_tema'], ),
    sa.PrimaryKeyConstraint('proposicao_id', 'tema_cod')
    )
    op.create_table('tema_ods',
    sa.Column('tema_cod', sa.Integer(), nullable=False),
    sa.Column('ods_numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tema_cod'], ['temas.cod_tema'], ),
    sa.PrimaryKeyConstraint('tema_cod', 'ods_numero')
    )
    op.add_column('projects', sa.Column('sincronizado', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_ano'), 'projects', ['ano'], unique=False)
    op.create_index(op.f('ix_projects_tipo'), 'projects', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tipo'), table_name='projects')
    op.drop_index(op.f('ix_projects_ano'), table_name='projects')
    op.drop_column('projects', 'sincronizado')
    op.drop_table('tema_ods')
    op.drop_table('proposicao_tema')
    op.drop_index(op.f('ix_classificacoes_id'), table_name='classificacoes')
    op.drop_table('classificacoes')
    op.drop_index(op.f('ix_temas_nome'), table_name='temas')
    op.drop_index(op.f('ix_temas_id'), table_name='temas')
    op.drop_index(op.f('ix_temas_cod_tema'), table_name='temas')
    op.drop_table('temas')
    op.drop_index(op.f('ix_tags_tipo_tag'), table_name='tags')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
