"""adiciona politician_id e tipo em notifications

Revision ID: e189d9e23dd3
Revises: 63d99557d618
Create Date: 2026-06-07 11:30:20.707923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e189d9e23dd3'
down_revision: Union[str, Sequence[str], None] = '63d99557d618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('politician_id', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('tipo', sa.String(), nullable=True))
    op.alter_column('notifications', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notifications', 'tipo')
    op.drop_column('notifications', 'politician_id')
    # ### end Alembic commands ###
